default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] %>

development:
  <<: *default
  database: ticket_selling_app_development

test:
  <<: *default
  database: ticket_selling_app_test

production:
  <<: *default
  database: ticket_selling_app_test
